### ISSUE TITLE
feat(patch): remove Reddit tracker

### ISSUE THREAD

**Issue by Amby713** [ReVanced/revanced-patches#1423]
### Application

Reddit official app

### Issue

Removes tracking 

### Patch

When sharing a link, it attaches the utm trackers at the end if the reddit link.
Ex:
 https://www.reddit.com/r/facepalm/comments/10fkyep/what_the_fuck_is_wrong_with_people/?utm_source=share&utm_medium=android_app&utm_name=androidcss&utm_term=1&utm_content=share_button

Have patch remove everything after "?" to look like this

https://www.reddit.com/r/facepalm/comments/10fkyep/what_the_fuck_is_wrong_with_people

### Motivation

Simplifies link sharing 

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
