### ISSUE TITLE
feat: Remove `si=` tracker id from YouTube's and YouTube Music's share link option

### ISSUE THREAD

**Issue by pcroland** [ReVanced/revanced-patches#281]
Currently both YouTube and YouTube Music copies URLs with a tracking ID. It would be nice if I didn't have to manually remove them when sharing an URL.

### Patch

Remove from `?si=...` from the copied URLs

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.
