### ISSUE TITLE
feat: Universal ad/tracker blocking (Android Activity/Service)

### ISSUE THREAD

**Issue by topminipie** [ReVanced/revanced-patches#3173]
### Feature description

Target applications: unlimited :)

Block ads using Android Activity/Service blocking.
As for me, this is a more universal way than removing links from the code. #1529
The signatures (Android Activity/Service) of many trackers are already known and there are clearly fewer of them than the domains of popular advertising networks. (https://etip.exodus-privacy.eu.org/trackers/all)

Example:
Google AdMob:
com.google.ads.|com.google.android.gms.ads|com.google.android.ads.|com.google.unity.ads.|com.google.android.gms.admob|com.google.firebase.firebase_ads

Google Analytics:
com.google.android.apps.analytics.|com.google.android.gms.analytics.|com.google.analytics

Google CrashLytics:
io.fabric.|com.crashlytics.|com.google.firebase.crashlytics|com.google.firebase.crash.|io.invertase.firebase.crashlytics

Google Firebase Analytics:
com.google.firebase.analytics.|com.google.android.gms.measurement.|com.google.firebase.firebase_analytics

Google Tag Manager:
com.google.tagmanager|com.google.android.gms.tagmanager

Branch:
io.branch

etc...

### Motivation

One patch for all applications.

Trackers are trackers.
They violate your rights to privacy, etc.

They are annoying and waste a lot of internet.

### Acknowledgements

- [ ] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by oSumAtrIX** [comment]
https://github.com/ReVanced/revanced-patches/issues/1529

**Comment by oSumAtrIX** [comment]
Add it as a comment

**Comment by kazimmt** [comment]
> ?

Comment your suggestion on #1529 
Then it'll be easy to track
