### ISSUE TITLE
bug(YouTube - Remove tracking query parameter): Tracking parameters are not removed

### ISSUE THREAD

**Issue by SodaWithoutSparkles** [ReVanced/revanced-patches#3238]
### Bug description

1. Upgrade to at least 4.8.2
2. Watch a video and use the share button
3. Select copy link as the method
4. Paste it and observe the `?si=` tracking parameter is still here

Example video: https://youtu.be/dQw4w9WgXcQ

### Additional context

I suppose this might be forgotten after implementing spoofing clients?

### Acknowledgements

- [X] This issue is not a duplicate of an existing bug report.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.

**Comment by SodaWithoutSparkles** [comment]
Strange... I'll attach a recording

**Comment by SodaWithoutSparkles** [comment]
Strange... I'll attach a recording

https://github.com/ReVanced/revanced-patches/assets/64138578/9144afaf-8764-4188-bbe3-3ea372ac0ee8

**Comment by SodaWithoutSparkles** [comment]
Spoofing 18.33.40 did not resolve the issue. Will try the others later

**Comment by SodaWithoutSparkles** [comment]
It seems that using dev patches resolved my issue somehow? I'll close this issue now
