### ISSUE TITLE
bug: Resource compilation fails when patching Meta apps with screen capture/screenshot patches

### ISSUE THREAD

**Issue by 0x33taji** [ReVanced/revanced-patches#4007]
### Bug description

When attempting to patch Meta apps (Facebook, Messenger, Instagram, WhatsApp) with screenshot/screen capture restriction removal patches, the patches apply successfully but fail during resource compilation. This occurs consistently across all Meta apps but with different resource-related errors for each app.
Steps to reproduce:

Download latest Meta apps APKs:

WhatsApp v2.24.22.79
Facebook v489.0.0.66.81
Messenger v483.0.0.62.109
Instagram v356.0.0.41.101

Use ReVanced CLI v5.0.0 with patches v5.1.0
Apply "Remove screenshot restriction" and "Remove screen capture restriction" patches
Observe resource compilation failures

Used patches:

Remove screenshot restriction
Remove screen capture restriction
Hide ads (Instagram)
Hide inbox ads (Messenger)
Hide story ads (Facebook)

### Error logs

```shell
Each Meta app fails differently during resource compilation:

WhatsApp error:
CopyWARNING: error: attribute state_with_icon (aka com.whatsapp:state_with_icon) not found.
WARNING: error: failed linking file resources.

Facebook/Messenger error:
CopyWARNING: error: invalid file path '[...]/res/color.2/APKTOOL_DUMMYVAL_0x7f170002.xml'
[Multiple similar errors]

Instagram error:
CopyWARNING: [...]/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference.
[Multiple similar errors]


Actual verbose error output:
$ ./patch_apk_v5.sh 
Patching com.facebook.orca_483.0.0.62.109-326613774_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk...
Output will be: messenger-revanced_483.0.0.62.109.apk
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: "Export all activities" disabled 
INFO: "Spoof build info" disabled 
INFO: "Hide mock location" disabled 
INFO: "Spoof SIM country" disabled 
INFO: "Spoof Wi-Fi connection" disabled 
INFO: "Enable Android debugging" disabled 
INFO: "Change data directory location" disabled 
INFO: "Hex" disabled 
INFO: "Predictive back gesture" disabled 
INFO: "Override certificate pinning" disabled 
INFO: "Change package name" disabled 
INFO: "Remove share targets" disabled 
INFO: "Change version code" disabled 
INFO: "Hide inbox subtabs" disabled 
WARNING: "Disable switching emoji to sticker" incompatible with com.facebook.orca 483.0.0.62.109 but compatible with com.facebook.orca 439.0.0.29.119 
INFO: "Disable typing indicator" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Hide inbox ads" succeeded 
INFO: "Remove screen capture restriction" succeeded 
INFO: "Remove screenshot restriction" succeeded 
INFO: Compiling modified resources 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170002.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170003.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170004.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170007.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170008.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170009.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000a.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000b.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000c.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f17000d.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170010.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170011.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170012.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170013.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170014.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170015.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170016.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170087.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f170088.xml'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res/color.2/APKTOOL_DUMMYVAL_0x7f1700ce.xml'. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_912996840641282149926747926407154376.tmp, compile, --dir, /home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.patch.ResourcePatchContext.get(ResourcePatchContext.kt:133)
        at app.revanced.patcher.Patcher.get(Patcher.kt:159)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:327)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_912996840641282149926747926407154376.tmp, compile, --dir, /home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/messenger-revanced_483.0.0.62.109-temporary-files/patcher/apk/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
Done patching com.facebook.orca_483.0.0.62.109-326613774_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk
-------------------
Patching com.facebook.katana_489.0.0.66.81-456819148_minAPI30(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk...
Output will be: facebook-revanced_489.0.0.66.81.apk
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: "Export all activities" disabled 
INFO: "Spoof build info" disabled 
INFO: "Hide mock location" disabled 
INFO: "Spoof SIM country" disabled 
INFO: "Spoof Wi-Fi connection" disabled 
INFO: "Enable Android debugging" disabled 
INFO: "Change data directory location" disabled 
INFO: "Hex" disabled 
INFO: "Predictive back gesture" disabled 
INFO: "Override certificate pinning" disabled 
INFO: "Change package name" disabled 
INFO: "Remove share targets" disabled 
INFO: "Change version code" disabled 
INFO: "Hide 'Sponsored Stories'" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Hide story ads" succeeded 
INFO: "Remove screen capture restriction" succeeded 
INFO: "Remove screenshot restriction" succeeded 
INFO: Compiling modified resources 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_ab_share_pack_mtrl_alpha.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_check_to_on_mtrl_000.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_check_to_on_mtrl_015.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_radio_to_on_mtrl_000.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_radio_to_on_mtrl_015.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_switch_to_on_mtrl_00001.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_btn_switch_to_on_mtrl_00012.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_cab_background_top_mtrl_alpha.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_ic_commit_search_api_mtrl_alpha.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_divider_mtrl_alpha.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_focused_holo.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_longpressed_holo.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_pressed_holo_dark.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_pressed_holo_light.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_selector_disabled_holo_dark.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_list_selector_disabled_holo_light.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_menu_hardkey_panel_mtrl_mult.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_popup_background_mtrl_mult.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_scrubber_control_off_mtrl_alpha.png'. 
WARNING: error: invalid file path '/home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res/drawable.2-xxhdpi/abc_scrubber_control_to_pressed_mtrl_000.png'. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6642032604993671108527957686205963201.tmp, compile, --dir, /home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.patch.ResourcePatchContext.get(ResourcePatchContext.kt:133)
        at app.revanced.patcher.Patcher.get(Patcher.kt:159)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:327)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_6642032604993671108527957686205963201.tmp, compile, --dir, /home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/facebook-revanced_489.0.0.66.81-temporary-files/patcher/apk/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
Done patching com.facebook.katana_489.0.0.66.81-456819148_minAPI30(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk
-------------------
Patching com.instagram.android_356.0.0.41.101-375614729_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk...
Output will be: instagram-revanced_356.0.0.41.101.apk
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: "Export all activities" disabled 
INFO: "Spoof build info" disabled 
INFO: "Hide mock location" disabled 
INFO: "Spoof SIM country" disabled 
INFO: "Spoof Wi-Fi connection" disabled 
INFO: "Enable Android debugging" disabled 
INFO: "Change data directory location" disabled 
INFO: "Hex" disabled 
INFO: "Predictive back gesture" disabled 
INFO: "Override certificate pinning" disabled 
INFO: "Change package name" disabled 
INFO: "Remove share targets" disabled 
INFO: "Change version code" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Hide ads" succeeded 
INFO: "Remove screen capture restriction" succeeded 
INFO: "Remove screenshot restriction" succeeded 
INFO: Compiling modified resources 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-h640dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-h640dp/layouts.xml: error: file failed to compile. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-land/layouts.xml: error: file failed to compile. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-sw600dp/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-sw600dp/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values-sw600dp/layouts.xml: error: file failed to compile. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:3: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:4: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:5: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:6: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:7: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:8: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:9: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:10: error: invalid value for type 'layout'. Expected a reference. 
WARNING: /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res/values/layouts.xml:11: error: invalid value for type 'layout'. Expected a reference. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5578077039799788359035017366791982354.tmp, compile, --dir, /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:123)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.patch.ResourcePatchContext.get(ResourcePatchContext.kt:133)
        at app.revanced.patcher.Patcher.get(Patcher.kt:159)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:327)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_5578077039799788359035017366791982354.tmp, compile, --dir, /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/res, --legacy, -o, /home/pi/git/revanced/patched/instagram-revanced_356.0.0.41.101-temporary-files/patcher/apk/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:119)
        ... 13 more
Done patching com.instagram.android_356.0.0.41.101-375614729_minAPI28(arm64-v8a)(360,400,420,480dpi)_apkmirror.com.apk
-------------------
Patching Telegram.apk...
Output will be: telegram-revanced_11.3.4.apk
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: "Export all activities" disabled 
INFO: "Spoof build info" disabled 
INFO: "Hide mock location" disabled 
INFO: "Spoof SIM country" disabled 
INFO: "Spoof Wi-Fi connection" disabled 
INFO: "Enable Android debugging" disabled 
INFO: "Change data directory location" disabled 
INFO: "Hex" disabled 
INFO: "Predictive back gesture" disabled 
INFO: "Override certificate pinning" disabled 
INFO: "Change package name" disabled 
INFO: "Remove share targets" disabled 
INFO: "Change version code" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Remove screen capture restriction" succeeded 
INFO: "Remove screenshot restriction" succeeded 
INFO: Compiling modified resources 
INFO: Aligning APK 
INFO: Signing APK 
INFO: Saved to /home/pi/git/revanced/patched/telegram-revanced_11.3.4.apk 
Done patching Telegram.apk
-------------------
Patching WhatsApp.apk...
Output will be: whatsapp-revanced_2.24.22.79.apk
INFO: Loading patches 
INFO: Decoding app manifest 
INFO: "Export all activities" disabled 
INFO: "Spoof build info" disabled 
INFO: "Hide mock location" disabled 
INFO: "Spoof SIM country" disabled 
INFO: "Spoof Wi-Fi connection" disabled 
INFO: "Enable Android debugging" disabled 
INFO: "Change data directory location" disabled 
INFO: "Hex" disabled 
INFO: "Predictive back gesture" disabled 
INFO: "Override certificate pinning" disabled 
INFO: "Change package name" disabled 
INFO: "Remove share targets" disabled 
INFO: "Change version code" disabled 
INFO: Setting patch options 
INFO: Deleting existing temporary files directory 
INFO: Decoding resources 
INFO: Initializing lookup maps 
INFO: Executing patches 
INFO: "Remove screen capture restriction" succeeded 
INFO: "Remove screenshot restriction" succeeded 
INFO: Compiling modified resources 
WARNING: /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/apk/res/drawable/mtrl_switch_thumb.xml:6: error: attribute state_with_icon (aka com.whatsapp:state_with_icon) not found. 
WARNING: error: failed linking file resources. 
brut.androlib.exceptions.AndrolibException: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_124852319438198211228626862287385802294.tmp, link, -o, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 242279021, --version-name, 2.24.22.79, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL1528573210501567982.tmp, -0, arsc, -I, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/1.apk, --manifest, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/apk/AndroidManifest.xml, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/apk/build/resources.zip]
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:249)
        at brut.androlib.AaptInvoker.invokeAapt(AaptInvoker.java:394)
        at app.revanced.patcher.patch.ResourcePatchContext.get(ResourcePatchContext.kt:133)
        at app.revanced.patcher.Patcher.get(Patcher.kt:159)
        at app.revanced.cli.command.PatchCommand.run(PatchCommand.kt:327)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2030)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2465)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2457)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2419)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2277)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2421)
        at picocli.CommandLine.execute(CommandLine.java:2174)
        at app.revanced.cli.command.MainCommandKt.main(MainCommand.kt:12)
Caused by: brut.common.BrutException: could not exec (exit code = 1): [/tmp/brut_util_Jar_124852319438198211228626862287385802294.tmp, link, -o, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/patched/resources/resources.apk, --package-id, 127, --min-sdk-version, 21, --target-sdk-version, 34, --version-code, 242279021, --version-name, 2.24.22.79, --no-auto-version, --no-version-vectors, --no-version-transitions, --no-resource-deduping, --allow-reserved-package-id, --warn-manifest-validation, -e, /tmp/APKTOOL1528573210501567982.tmp, -0, arsc, -I, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/1.apk, --manifest, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/apk/AndroidManifest.xml, /home/pi/git/revanced/patched/whatsapp-revanced_2.24.22.79-temporary-files/patcher/apk/build/resources.zip]
        at brut.util.OS.exec(OS.java:104)
        at brut.androlib.AaptInvoker.invokeAapt2(AaptInvoker.java:245)
        ... 13 more
Done patching WhatsApp.apk
-------------------
All patching operations completed!
```

### Additional context

Additional context:

The patches themselves apply successfully (as shown by "succeeded" messages during runtime)
Non-Meta apps (e.g., Telegram) patch successfully with the same patches
Issue appears to be with resource handling specific to Meta apps
System: x86_64 architecture running Debian stable
Java version: JRE 11
CLI version: 5.0.0
Patches version: 5.1.0

### Acknowledgements

- [x] I have checked all open and closed bug reports and this is not a duplicate.
- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.

**Comment by nightznero** [comment]
You can manually mod dex files and test if its works;

`invoke-virtual (\{.*\}), Landroid/view/Window;->addFlags\(I\)V`
and 
`invoke-virtual (\{.*\}), Landroid/view/Window;->setFlags\(II\)V`

Replace:
`#$1`
