### ISSUE TITLE
feat(patch): remove tracking service from reddit 

### ISSUE THREAD

**Issue by BigDogg99** [revanced/revanced-patches#735]
### Application

for pervent tracking

### Issue

reddit tracking uses more bettery and data affect performance

### Patch

thses are some tracker
api2.branch.io 
e.reddit.com
crashlyticsreports-pa.googleapis.com

### Motivation

I will make it bettery efficient , give us peace of mind

### Acknowledgements

- [ ] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by oSumAtrIX** [comment]
Dupe of #429.

**Comment by oSumAtrIX** [comment]
It is still a tracking removal request, extend the existing issue instead of creating a duplicate.

**Comment by SodaWithoutSparkles** [comment]
This [reddit post](https://www.reddit.com/r/pihole/comments/tolq3g/fyi_it_seems_that_the_reddit_app_is_responsible/) also discuss on api2.branch.io tracking. apprently its way more common, not only reddit but some other apps also use it
