### ISSUE TITLE
bug: (youtube/remove-tracking-query-parameter) tracking parameter is still present when sharing to external apps

### ISSUE THREAD

**Issue by n1cKz1** [ReVanced/revanced-patches#93]
### Bug description

Tracking query parameter is gone using the copy link button on yt's share menu, but is still present in links when sharing to external apps directly (e.g messenger)

Steps:
1. Tap on any vid
2. Tap on share button
3. Share on any external app

### Acknowledgements

- [X] This request is not a duplicate of an existing issue.
- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
